# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
      - master
      - dev
    machine:
      image: true

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install python 3.6
          command: |
            sudo add-apt-repository ppa:deadsnakes/ppa
            sudo apt-get update
            sudo apt-get install python3.6
            curl https://bootstrap.pypa.io/get-pip.py | sudo python3.6

      - run:
          name: Install dependencies
          command: |
            sudo python3.6 -m pip install -r requirements.txt

      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Start containers and verify they are working
          command: |
            set -x
            docker-compose -f docker-compose-dev.yml up -d --build
            echo "Wait for 5 sec for servers to spin up"
            sleep 5
            curl --retry 2 --retry-delay 1 http://localhost:5000/hw

      - run:
          name: Run pytest
          command: |
            python3.6 -m pytest tests/

      - run:
        name: Deploy to Docker Hub (dev)
        command: |
          if [ "${CIRCLE_BRANCH}" == "dev" ];
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f docker-compose-dev.yml push
          fi

      - run:
        name: Deploy to Docker Hub (master)
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ];
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f docker-compose-prod.yml  build
            docker-compose -f docker-compose-prod.yml  push
          fi

